apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eurekaserver
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_backend: "true"
        io.kompose.service: eurekaserver
    spec:
      containers:
      - image: 81XXXXXXXX3.dkr.ecr.us-east-2.amazonaws.com/ostock/eurekaserver:latest
        imagePullPolicy: ""
        name: eurekaserver
        ports:
        - containerPort: 8070
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
