apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  type: NodePort
  ports:
  - name: "8070"
    port: 8070
    targetPort: 8070
    nodePort: 31100
  selector:
    io.kompose.service: eurekaserver
status:
  loadBalancer: {}
